from django.urls import path
from .views import (
    StudyCreateView,
    StudyDetailView,
    StudyJoinView,
    StudyLeaveView,
    StudyListView,
    StudyMemberListView,
    StudyMemberKickView,
    StudyOwnerTransferView,
)

urlpatterns = [
    path(
        "studies/",
        StudyCreateView.as_view(),
        name="study_create",
    ),
    path(
        "studies/join/",
        StudyJoinView.as_view(),
        name="study_join",
    ),
    path(
        "studies/me/",
        StudyListView.as_view(),
        name="study_list",
    ),
    path(
        "studies/<int:study_id>/",
        StudyDetailView.as_view(),
        name="study_detail",
    ),
    path(
        "studies/<int:study_id>/leave/",
        StudyLeaveView.as_view(),
        name="study_leave",
    ),
    path(
        "studies/<int:study_id>/members/",
        StudyMemberListView.as_view(),
        name="study_member_list",
    ),
    path(
        "studies/<int:study_id>/members/<int:member_id>/",
        StudyMemberKickView.as_view(),
        name="study_member_kick",
    ),
    path(
        "studies/<int:study_id>/members/<int:member_id>/owner/",
        StudyOwnerTransferView.as_view(),
        name="study_owner_transfer",
    ),
]
