# Generated by Django 5.2.8 on 2025-11-25 01:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boj_number",
                    models.IntegerField(
                        db_index=True, unique=True, verbose_name="백준 문제 번호"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="문제 제목")),
                ("tier", models.CharField(max_length=20, verbose_name="티어")),
                ("link", models.URLField(verbose_name="문제 링크")),
            ],
            options={
                "verbose_name": "문제",
                "verbose_name_plural": "문제들",
                "db_table": "problems",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="이메일"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("github", "GitHub")],
                        max_length=20,
                        verbose_name="소셜 로그인 제공자",
                    ),
                ),
                (
                    "boj_username",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="백준 사용자명",
                    ),
                ),
                (
                    "profile_img_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="프로필 이미지 URL"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자들",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="스터디명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "invite_code",
                    models.CharField(
                        db_index=True,
                        max_length=8,
                        unique=True,
                        verbose_name="초대 코드",
                    ),
                ),
                (
                    "daily_problem_count",
                    models.IntegerField(default=3, verbose_name="일일 문제 수"),
                ),
                (
                    "target_tier",
                    models.CharField(max_length=20, verbose_name="목표 티어"),
                ),
                (
                    "template_content",
                    models.TextField(
                        default="## 접근 방법\n\n## 코드\n\n## 회고",
                        verbose_name="템플릿 내용",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_studies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="소유자",
                    ),
                ),
            ],
            options={
                "verbose_name": "스터디",
                "verbose_name_plural": "스터디들",
                "db_table": "studies",
            },
        ),
        migrations.CreateModel(
            name="SolutionNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_notes",
                        to="core.problem",
                        verbose_name="문제",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_notes",
                        to="core.study",
                        verbose_name="스터디",
                    ),
                ),
            ],
            options={
                "verbose_name": "풀이 노트",
                "verbose_name_plural": "풀이 노트들",
                "db_table": "solution_notes",
                "ordering": ["-created_at"],
                "unique_together": {("study", "user", "problem")},
            },
        ),
        migrations.CreateModel(
            name="DailyAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateField(db_index=True, verbose_name="할당일"),
                ),
                (
                    "is_custom",
                    models.BooleanField(default=False, verbose_name="커스텀 문제 여부"),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.problem",
                        verbose_name="문제",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_assignments",
                        to="core.study",
                        verbose_name="스터디",
                    ),
                ),
            ],
            options={
                "verbose_name": "일일 과제",
                "verbose_name_plural": "일일 과제들",
                "db_table": "daily_assignments",
                "ordering": ["-assigned_date"],
                "unique_together": {("study", "problem", "assigned_date")},
            },
        ),
        migrations.CreateModel(
            name="StudyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("member", "Member")],
                        max_length=10,
                        verbose_name="역할",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입일시"),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.study",
                        verbose_name="스터디",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "스터디 멤버",
                "verbose_name_plural": "스터디 멤버들",
                "db_table": "study_members",
                "unique_together": {("study", "user")},
            },
        ),
    ]
