# Generated by Django 5.2.8 on 2025-12-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="provider",
            field=models.CharField(
                choices=[("github", "GitHub"), ("google", "Google")],
                max_length=20,
                verbose_name="소셜 로그인 제공자",
            ),
        ),
    ]
