# Generated by Django 5.2.8 on 2025-12-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_img_url",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="프로필 이미지 URL"
            ),
        ),
    ]
