# Generated by Django 5.2.8 on 2025-12-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="boj_username",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="백준 사용자명",
            ),
        ),
    ]
