# Generated by Django 5.2.8

from django.db import migrations, models


def set_default_tier_values(apps, schema_editor):
    """기존 Study 인스턴스에 기본 티어 값 설정"""
    Study = apps.get_model("core", "Study")
    Study.objects.filter(tier_min__isnull=True).update(tier_min=0)
    Study.objects.filter(tier_max__isnull=True).update(tier_max=30)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_profile_img_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="study",
            name="target_tier",
        ),
        migrations.AddField(
            model_name="study",
            name="tier_min",
            field=models.IntegerField(null=True, verbose_name="문제 최소 티어"),
        ),
        migrations.AddField(
            model_name="study",
            name="tier_max",
            field=models.IntegerField(null=True, verbose_name="문제 최대 티어"),
        ),
        migrations.AddField(
            model_name="study",
            name="min_solved",
            field=models.IntegerField(blank=True, null=True, verbose_name="최소 푼 사람 수"),
        ),
        migrations.AddField(
            model_name="study",
            name="max_solved",
            field=models.IntegerField(blank=True, null=True, verbose_name="최대 푼 사람 수"),
        ),
        migrations.RunPython(set_default_tier_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="study",
            name="tier_min",
            field=models.IntegerField(verbose_name="문제 최소 티어"),
        ),
        migrations.AlterField(
            model_name="study",
            name="tier_max",
            field=models.IntegerField(verbose_name="문제 최대 티어"),
        ),
    ]
