# Generated by Django 5.2.8 on 2025-12-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_study_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='max_solved',
            field=models.IntegerField(blank=True, null=True, verbose_name='추천 문제 최대 푼 사람 수'),
        ),
        migrations.AlterField(
            model_name='study',
            name='min_solved',
            field=models.IntegerField(blank=True, null=True, verbose_name='추천 문제 최소 푼 사람 수'),
        ),
        migrations.AlterField(
            model_name='study',
            name='tier_max',
            field=models.IntegerField(verbose_name='추천 문제 최대 티어'),
        ),
        migrations.AlterField(
            model_name='study',
            name='tier_min',
            field=models.IntegerField(verbose_name='추천 문제 최소 티어'),
        ),
    ]
