# Generated by Django 5.2.8 on 2025-12-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_study_max_solved_alter_study_min_solved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='last_problem_refreshed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 문제 갱신 시간'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tier',
            field=models.IntegerField(verbose_name='티어'),
        ),
    ]
