# Generated by Django 5.2.8 on 2025-12-23 03:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_study_last_problem_refreshed_at_alter_problem_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일시'),
            preserve_default=False,
        ),
    ]
