# Generated by Django 5.2.8 on 2025-12-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_dailyassignment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionnote',
            name='assigned_date',
            field=models.DateField(blank=True, null=True, verbose_name='문제 배정일'),
        ),
    ]
