# Generated by Django 5.2.8 on 2026-01-21 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_study_template_content_problemsolvingstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField(verbose_name='리뷰 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('solution_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_review', to='core.solutionnote', verbose_name='풀이 노트')),
            ],
            options={
                'verbose_name': '코드 리뷰',
                'verbose_name_plural': '코드 리뷰들',
                'db_table': 'code_reviews',
            },
        ),
    ]
