# Generated by Django 5.2.8 on 2026-01-22 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_codereview"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CodeReview",
            new_name="SolutionNoteReview",
        ),
        migrations.AlterModelTable(
            name="solutionnotereview",
            table="solution_note_reviews",
        ),
        migrations.AlterModelOptions(
            name="solutionnotereview",
            options={
                "verbose_name": "풀이 노트 리뷰",
                "verbose_name_plural": "풀이 노트 리뷰들",
            },
        ),
        migrations.AlterField(
            model_name="solutionnotereview",
            name="solution_note",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solution_note_review",
                to="core.solutionnote",
                verbose_name="풀이 노트",
            ),
        ),
    ]
